apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: multi-k8s-iamsirid-com-tls
spec:
  secretName: multi-k8s-iamsirid-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.iamsirid.com
  dnsNames:
    - multi-k8s.iamsirid.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s.iamsirid.com
